### ISSUE TITLE
Keycloak certificate download can be automated

### ISSUE THREAD

**Issue by darius-m** [Zimbra/keycloak#3]
The process of downloading the IdP certificate can be mostly automated using a one-liner such as this:
```bash
curl -s https://keycloak.barrydegraaff.tk/auth/realms/master/protocol/saml/descriptor | \
    xmllint --xpath "//*[name()='ds:X509Certificate']/text()" - | \
    base64 -d | \
    openssl x509 -inform DER -outform PEM
```

**Comment by ghost** [comment]
Thanks I have added this to the guide as of now https://github.com/Zimbra/keycloak/commit/912f6fa7a43c935205d075c9f463978fe5a4d7bb
